app_key: <%= ENV['app_key'] %>
app_secret: <%= ENV['app_secret'] %>
access_token: <%= ENV['access_token'] %>
access_token_secret: <%= ENV['access_token_secret'] %>
user_id: <%= ENV['user_id'] %>
access_type: <%= ENV['access_type'] %>